// ═══════════════════════════════════════════════════
// SAMOA DPI — CANONICAL GOVERNMENT NODE REGISTRY
// Single source of truth for all 55 government nodes.
// All frontend apps import from this file.
// Contracts: contracts/script/Step2_MinistryNodes.s.sol
// Observers: contracts/script/Step3_WireAndSeed.s.sol
// Updated: feat/currency-architecture branch
// ═══════════════════════════════════════════════════

export type NodeType = 'OPERATIONAL' | 'OBSERVER' | 'REGULATORY'
export type GovBranch =
  | 'EXECUTIVE'
  | 'LEGISLATIVE'
  | 'JUDICIAL'
  | 'REGULATORY'
  | 'SOE'
  | 'ACADEMIC'

export interface GovernmentNode {
  code:        string
  name:        string
  branch:      GovBranch
  nodeType:    NodeType
  color:       string
  role?:       string
  description: string
  phase:       1 | 2 | 3
  addrKey:     string
}

export const GOVERNMENT_NODES: GovernmentNode[] = [

  // ─── REGULATORY AUTHORITIES ──────────────────────
  {
    code: 'CBS',
    name: 'Central Bank of Samoa',
    branch: 'REGULATORY',
    nodeType: 'REGULATORY',
    color: '#C9A227',
    role: 'ADMIN — Monetary Authority',
    description: 'CBDC issuer, system administrator, monetary policy authority. Holds ADMIN role across all 4 contracts.',
    phase: 1,
    addrKey: 'CBS',
  },
  {
    code: 'SIFA',
    name: 'Samoa International Finance Authority',
    branch: 'REGULATORY',
    nodeType: 'OBSERVER',
    color: '#9C6BDA',
    role: 'AML + Offshore Finance Regulator',
    description: 'Public Trading Body reclassified 2020. Regulates offshore financial services, generates dividend revenue. Key for FATF compliance.',
    phase: 2,
    addrKey: 'SIFA',
  },
  {
    code: 'AUDIT',
    name: 'Samoa Audit Office',
    branch: 'REGULATORY',
    nodeType: 'OBSERVER',
    color: '#8A9BBD',
    role: 'Audit Trail Consumer',
    description: 'Independent audit authority. Receives on-chain audit trail exports for government financial oversight.',
    phase: 2,
    addrKey: 'AUDIT',
  },
  {
    code: 'OMBUDS',
    name: 'Office of the Ombudsman',
    branch: 'REGULATORY',
    nodeType: 'OBSERVER',
    color: '#8A9BBD',
    role: 'Complaint Oversight',
    description: 'Independent oversight of government administration. Observer access to service record disputes.',
    phase: 2,
    addrKey: 'OMBUDS',
  },
  {
    code: 'OOTR',
    name: 'Office of the Regulator',
    branch: 'REGULATORY',
    nodeType: 'OBSERVER',
    color: '#00C4B4',
    role: 'Telecom + Broadcast Regulator',
    description: 'Regulates telecommunications, broadcasting, spectrum, postal services. Independent of MCIT. Relevant for digital infrastructure layer.',
    phase: 2,
    addrKey: 'OOTR',
  },

  // ─── EXECUTIVE MINISTRIES — Phase 1 ─────────────
  {
    code: 'MCIT',
    name: 'Ministry of Communications and Information Technology',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#003087',
    role: 'Digital Infrastructure',
    description: 'Oversees telecommunications regulation, Broadcasting Services Division (Radio 2AP + TV9), Samoa Post, digital infrastructure policy.',
    phase: 1,
    addrKey: 'MCIT',
  },
  {
    code: 'MOF',
    name: 'Ministry of Finance',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#00793D',
    role: 'Fund Release Authority',
    description: 'All government fund releases flow through MOF. Oversees CBS, SIFA, SNPF, DBS, SHC, PAL portfolio. Authorises tranche releases after MWTI verification.',
    phase: 1,
    addrKey: 'MOF',
  },
  {
    code: 'MCIL',
    name: 'Ministry of Commerce, Industry and Labour',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#CE1126',
    role: 'Business Registration',
    description: 'Business registration, licensing, labour regulation. Oversees ACC, Samoa Tourism Authority, Commerce Commission.',
    phase: 1,
    addrKey: 'MCIL',
  },
  {
    code: 'MESC',
    name: 'Ministry of Education and Culture',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#00A090',
    role: 'Education Records',
    description: 'Education policy and records. Links to SQA (qualifications), NUS (university). Manages National University of Samoa portfolio.',
    phase: 1,
    addrKey: 'EDUCATION',
  },
  {
    code: 'CUSTOMS',
    name: 'Ministry of Customs',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#F59E0B',
    role: 'Trade Clearances',
    description: 'Customs clearance, trade facilitation. Separate from Revenue (MOR) as of 2025 cabinet restructure.',
    phase: 1,
    addrKey: 'CUSTOMS',
  },
  {
    code: 'SBS',
    name: 'Samoa Bureau of Statistics',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#8A9BBD',
    role: 'National Statistics',
    description: 'National statistics authority. Under MWCSD portfolio. Provides population and economic data for DPI analytics layer.',
    phase: 1,
    addrKey: 'SBS',
  },
  {
    code: 'NDIDS',
    name: 'National Digital Identity System',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#4FC3F7',
    role: 'Identity Registry',
    description: 'NDIDSRegistry.sol — citizen identity by cryptographic hash. Foundation layer for all service access and credential verification.',
    phase: 1,
    addrKey: 'NDIDS',
  },

  // ─── EXECUTIVE MINISTRIES — Phase 2 ─────────────
  {
    code: 'MPMC',
    name: 'Ministry of the Prime Minister and Cabinet',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#C9A227',
    role: 'Policy Authority',
    description: 'Cross-government policy coordination, immigration services, government media (Savali newspaper, Press Secretariat). PM holds MFAT and Police portfolios.',
    phase: 2,
    addrKey: 'MPMC',
  },
  {
    code: 'MOH',
    name: 'Ministry of Health',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#00A651',
    role: 'Health Policy',
    description: 'Health policy and regulation. NHS delivers health services operationally. Links to NDIDS for patient identity.',
    phase: 2,
    addrKey: 'MOH',
  },
  {
    code: 'MWTI',
    name: 'Ministry of Works, Transport and Infrastructure',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#FF8C00',
    role: 'Project Verifier',
    description: 'Infrastructure project verification. IProjectVerification implementor — MWTI attests project milestones before MOF releases funds. Oversees SAA, SPA, SSC portfolio.',
    phase: 2,
    addrKey: 'MWTI',
  },
  {
    code: 'MOJ',
    name: 'Ministry of Justice, Courts and Administration',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#5C3B00',
    role: 'Legal Records',
    description: 'Justice administration, court records, electoral commission oversight. Public Trust Office under this portfolio.',
    phase: 2,
    addrKey: 'MOJ',
  },
  {
    code: 'MOR',
    name: 'Ministry of Revenue',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#7040A8',
    role: 'Tax Clearances',
    description: 'Tax clearance certificates, revenue collection. Separate ministry from Customs as of 2025. Samoa Revenue Service operational arm.',
    phase: 2,
    addrKey: 'MOR',
  },
  {
    code: 'MFAT',
    name: 'Ministry of Foreign Affairs and Trade',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#003087',
    role: 'Trade Permits',
    description: 'Foreign affairs, trade permits, diplomatic coordination. Under PM portfolio. Links to Samoa Export Authority.',
    phase: 2,
    addrKey: 'MFAT',
  },
  {
    code: 'MAF',
    name: 'Ministry of Agriculture and Fisheries',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#00793D',
    role: 'Rural Grants',
    description: 'Agriculture and fisheries policy, rural development grants. Oversees SROS (Scientific Research Organisation).',
    phase: 2,
    addrKey: 'MAF',
  },
  {
    code: 'MWCSD',
    name: 'Ministry of Women, Community and Social Development',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#E8445A',
    role: 'Social Grants',
    description: 'Community grants, social services, Village Mayors, Births/Deaths/Marriages registry. Oversees SBS.',
    phase: 2,
    addrKey: 'MWCSD',
  },
  {
    code: 'MPE',
    name: 'Ministry of Public Enterprises',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#C9A227',
    role: 'SOE Governance Hub',
    description: 'Governance and oversight of all 27 public bodies. Issues Letters of Expectation to all SOE boards. Key coordinating ministry for DPI SOE integration.',
    phase: 2,
    addrKey: 'MPE',
  },
  {
    code: 'MLS',
    name: 'Ministry of Lands and Survey',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#7A5F18',
    role: 'Land Title Records',
    description: 'Land title registration, survey records, customary land advisory. STEC transitioning to this ministry. Critical for Samoa land tenure system.',
    phase: 2,
    addrKey: 'MLS',
  },
  {
    code: 'MNRE',
    name: 'Ministry of Natural Resources and Environment',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#00A651',
    role: 'Environmental Permits',
    description: 'Environmental permits, national parks, forestry, meteorology, water conservation. Links to MNRE emergency broadcasts via Radio 2AP.',
    phase: 2,
    addrKey: 'MNRE',
  },
  {
    code: 'POLICE',
    name: 'Samoa Police Service',
    branch: 'EXECUTIVE',
    nodeType: 'OPERATIONAL',
    color: '#CE1126',
    role: 'Police Clearances',
    description: 'Police clearance certificates — highest citizen demand service. Traffic enforcement links to LTA. Under PM portfolio.',
    phase: 2,
    addrKey: 'POLICE',
  },

  // ─── PUBLIC BENEFICIAL BODIES — Operational ──────
  {
    code: 'SQA',
    name: 'Samoa Qualifications Authority',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#00A090',
    role: 'Qualification Registry',
    description: 'Authoritative body for all qualification verification in Samoa. Established SQA Act 2010. High diaspora use case — NZ/AU credential verification. Under MPE governance.',
    phase: 2,
    addrKey: 'SQA',
  },
  {
    code: 'LTA',
    name: 'Land Transport Authority',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#F59E0B',
    role: 'Vehicle + Driver Registry',
    description: 'Vehicle registration and driver licensing. Highest daily citizen transaction volume. Established 2008 from MWTI/TCB merger. Under MPE governance.',
    phase: 2,
    addrKey: 'LTA',
  },
  {
    code: 'NHS',
    name: 'National Health Services',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#00A651',
    role: 'Health Service Delivery',
    description: 'Operational health service delivery — hospitals, district health centres. Policy arm is MOH. Under MPE governance.',
    phase: 2,
    addrKey: 'NHS',
  },
  {
    code: 'STA',
    name: 'Samoa Tourism Authority',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#CE1126',
    role: 'Tourism Licensing',
    description: 'Tourism licensing, permits, promotion. Under MCIL portfolio. Links to MFAT for international trade.',
    phase: 2,
    addrKey: 'STA',
  },

  // ─── SOEs — Operational ──────────────────────────
  {
    code: 'DBS',
    name: 'Development Bank of Samoa',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#003087',
    role: 'WST-DPI Retail Distributor',
    description: 'Retail distribution layer for WST-DPI Digital Tala. CBS issues wholesale, DBS distributes retail. Under MOF portfolio. Dashboard: apps/dbs/',
    phase: 2,
    addrKey: 'DBS',
  },
  {
    code: 'SLC',
    name: 'Samoa Land Corporation',
    branch: 'SOE',
    nodeType: 'OPERATIONAL',
    color: '#7A5F18',
    role: 'Land Asset Management',
    description: 'Manages 24,000 acres of government land. Established 1990 post-WESTEC restructure. Under MPE. Divests land commercially for socio-economic development.',
    phase: 2,
    addrKey: 'SLC',
  },

  // ─── LEGISLATIVE BRANCH — Observers ──────────────
  {
    code: 'LEGIS',
    name: 'Legislative Assembly of Samoa',
    branch: 'LEGISLATIVE',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Parliamentary Oversight',
    description: '49-seat Parliament. Fono. Oversight of all government expenditure. Read access to grant disbursement records.',
    phase: 2,
    addrKey: 'LEGIS',
  },
  {
    code: 'FINCOM',
    name: 'Parliamentary Finance Committee',
    branch: 'LEGISLATIVE',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Grant Oversight + Governance Participant',
    description: 'Finance Committee reviews government expenditure. Potential multisig governance participant for large grant approvals.',
    phase: 2,
    addrKey: 'FINCOM',
  },
  {
    code: 'ATTGEN',
    name: 'Office of the Attorney General',
    branch: 'LEGISLATIVE',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Legal Authority',
    description: 'Legal advisor to government. Relevant for contract legal wrapper (BIS-P11) and smart contract legal authority mapping.',
    phase: 2,
    addrKey: 'ATTGEN',
  },

  // ─── JUDICIAL BRANCH — Observers ─────────────────
  {
    code: 'LTC',
    name: 'Land and Titles Court',
    branch: 'JUDICIAL',
    nodeType: 'OBSERVER',
    color: '#5C3B00',
    role: 'Customary Land Records',
    description: 'Critical for Samoa — customary land tenure disputes. Read access to MLS land records. Future: on-chain customary title verification.',
    phase: 2,
    addrKey: 'LTC',
  },
  {
    code: 'SCOURT',
    name: 'Supreme Court of Samoa',
    branch: 'JUDICIAL',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Legal Record Observer',
    description: 'Highest court. Observer access for legal record verification and smart contract dispute context.',
    phase: 2,
    addrKey: 'SCOURT',
  },
  {
    code: 'ELECTC',
    name: 'Office of the Electoral Commissioner',
    branch: 'JUDICIAL',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Electoral Records',
    description: 'Electoral roll management. Links to NDIDS for voter identity verification in Phase 3.',
    phase: 2,
    addrKey: 'ELECTC',
  },
  {
    code: 'PTO',
    name: 'Public Trust Office',
    branch: 'JUDICIAL',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Estate + Trust Records',
    description: 'Manages deceased estates and trusts. Under MOJ portfolio. Links to MLS land records for estate land management.',
    phase: 2,
    addrKey: 'PTO',
  },

  // ─── SOE / PUBLIC TRADING BODIES — Observers ─────
  {
    code: 'EPC',
    name: 'Electric Power Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#F59E0B',
    role: 'Utility Payments',
    description: '2025 electricity crisis highlighted infrastructure risk. Future utility payment integration via WST-DPI.',
    phase: 3,
    addrKey: 'EPC',
  },
  {
    code: 'SWA',
    name: 'Samoa Water Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#4FC3F7',
    role: 'Water Utility',
    description: 'Water utility services. Future utility payment integration.',
    phase: 3,
    addrKey: 'SWA',
  },
  {
    code: 'SAA',
    name: 'Samoa Airport Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#003087',
    role: 'Airport Operations',
    description: 'Faleolo International Airport operations. Under MWTI portfolio. Links to immigration and travel services.',
    phase: 3,
    addrKey: 'SAA',
  },
  {
    code: 'SPA',
    name: 'Samoa Ports Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#003087',
    role: 'Port Operations',
    description: 'Apia port operations. Under MWTI portfolio. Trade and customs integration. Infrastructure bottleneck flagged 2025.',
    phase: 3,
    addrKey: 'SPA',
  },
  {
    code: 'SSC',
    name: 'Samoa Shipping Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#003087',
    role: 'Inter-island Shipping',
    description: 'Inter-island and international shipping. Under MWTI portfolio.',
    phase: 3,
    addrKey: 'SSC',
  },
  {
    code: 'SHC',
    name: 'Samoa Housing Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#00793D',
    role: 'Housing Grants',
    description: 'Government housing development and loans. Under MOF portfolio. Links to MLS land records and MOF grant disbursement.',
    phase: 3,
    addrKey: 'SHC',
  },
  {
    code: 'SNPF',
    name: 'Samoa National Provident Fund',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#7040A8',
    role: 'Superannuation Records',
    description: 'National superannuation scheme. Public mutual body. Under MOF portfolio. High citizen data sensitivity.',
    phase: 3,
    addrKey: 'SNPF',
  },
  {
    code: 'ACC',
    name: 'Accident Compensation Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#E8445A',
    role: 'Workers Compensation',
    description: 'Accident compensation scheme. Under MCIL portfolio. Beneficial body status.',
    phase: 3,
    addrKey: 'ACC',
  },
  {
    code: 'PAL',
    name: 'Polynesian Airlines Ltd',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#CE1126',
    role: 'Air Transport',
    description: 'Operates as Samoa Airways. Under MOF portfolio. Air travel records for immigration integration.',
    phase: 3,
    addrKey: 'PAL',
  },
  {
    code: 'UTOS',
    name: 'Unit Trust of Samoa',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#C9A227',
    role: 'Investment Fund',
    description: 'Government investment fund vehicle. Under MOF portfolio.',
    phase: 3,
    addrKey: 'UTOS',
  },
  {
    code: 'SLAC',
    name: 'Samoa Life Assurance Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#7040A8',
    role: 'Life Insurance',
    description: 'Public mutual body. Under MOF portfolio.',
    phase: 3,
    addrKey: 'SLAC',
  },
  {
    code: 'STEC',
    name: 'Samoa Trust Estates Corporation',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#7A5F18',
    role: 'Estate Management',
    description: 'Transitioning to Ministry of Lands and Survey (MLS). Historical land estate management.',
    phase: 3,
    addrKey: 'STEC',
  },
  {
    code: 'POST',
    name: 'Samoa Post',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#CE1126',
    role: 'Postal Services',
    description: 'Government postal service. Under MCIT portfolio.',
    phase: 3,
    addrKey: 'POST',
  },

  // ─── PUBLIC BENEFICIAL BODIES — Observers ────────
  {
    code: 'SFES',
    name: 'Samoa Fire and Emergency Services',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#E8445A',
    role: 'Emergency Services',
    description: 'Fire and emergency response. Under PM portfolio.',
    phase: 3,
    addrKey: 'SFES',
  },
  {
    code: 'SSFA',
    name: 'Samoa Sports Facilities Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#00A090',
    role: 'Sports Infrastructure',
    description: 'Sports facilities management. Under Sports portfolio.',
    phase: 3,
    addrKey: 'SSFA',
  },
  {
    code: 'SEA',
    name: 'Samoa Export Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#00793D',
    role: 'Export Development',
    description: 'New body replacing STEC export functions. Promotes Samoa exports internationally. Under PM portfolio.',
    phase: 3,
    addrKey: 'SEA',
  },
  {
    code: 'GCA',
    name: 'Gambling Control Authority',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#4A5878',
    role: 'Gaming Licences',
    description: 'Gambling regulation and licensing. Under MCIL portfolio.',
    phase: 3,
    addrKey: 'GCA',
  },
  {
    code: 'NKF',
    name: 'National Kidney Foundation of Samoa',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#E8445A',
    role: 'Health Beneficial Body',
    description: 'Kidney disease support and treatment. Beneficial body under MOH sector.',
    phase: 3,
    addrKey: 'NKF',
  },
  {
    code: 'SROS',
    name: 'Scientific Research Organisation of Samoa',
    branch: 'SOE',
    nodeType: 'OBSERVER',
    color: '#00A090',
    role: 'Scientific Research',
    description: 'National scientific research body. Under MAF portfolio.',
    phase: 3,
    addrKey: 'SROS',
  },
]

// ─── Derived helpers ──────────────────────────────

export const OPERATIONAL_NODES = GOVERNMENT_NODES
  .filter(n => n.nodeType === 'OPERATIONAL')

export const OBSERVER_NODES = GOVERNMENT_NODES
  .filter(n => n.nodeType === 'OBSERVER')

export const REGULATORY_NODES = GOVERNMENT_NODES
  .filter(n => n.nodeType === 'REGULATORY')

export const nodesByBranch = (branch: GovBranch) =>
  GOVERNMENT_NODES.filter(n => n.branch === branch)

export const nodeByCode = (code: string) =>
  GOVERNMENT_NODES.find(n => n.code === code)

export const PHASE_1_NODES = GOVERNMENT_NODES
  .filter(n => n.phase === 1)

export const PHASE_2_NODES = GOVERNMENT_NODES
  .filter(n => n.phase === 2)

// Key nodes for Three.js canvas ring
// (CBS centre + 7 highest-visibility operational nodes)
export const CANVAS_RING_NODES = [
  'MOF', 'MWTI', 'MCIT', 'NDIDS',
  'DBS', 'POLICE', 'SQA', 'LTA',
].map(code => nodeByCode(code)!)
  .filter(Boolean)
